import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BattleState } from '../../types';
import './BattleUI.css';
export const BattleUI = ({ playerHp, playerMaxHp, enemyHp, enemyMaxHp, battleState, enemyName = '史莱姆', }) => {
    const playerPercent = Math.max(0, Math.min(100, (playerHp / playerMaxHp) * 100));
    const enemyPercent = Math.max(0, Math.min(100, (enemyHp / enemyMaxHp) * 100));
    const isFighting = battleState === BattleState.FIGHTING;
    const isWon = battleState === BattleState.WON;
    const isLost = battleState === BattleState.LOST;
    return (_jsxs("div", { className: "battle-ui", children: [_jsxs("div", { className: "battle-top-bar", children: [_jsxs("div", { className: "hp-section player-section", children: [_jsxs("div", { className: "section-header", children: [_jsx("span", { className: "player-icon", children: "\uD83D\uDC64" }), _jsx("span", { className: "character-name player-name", children: "\u73A9\u5BB6" })] }), _jsxs("div", { className: "hp-bar-container", children: [_jsx("div", { className: "hp-bar player", children: _jsx("div", { className: "hp-fill", style: { width: `${playerPercent}%` } }) }), _jsxs("span", { className: "hp-text", children: [playerHp, "/", playerMaxHp] })] })] }), _jsx("div", { className: "vs-divider", children: _jsx("span", { className: "vs-text", children: "VS" }) }), _jsxs("div", { className: "hp-section enemy-section", children: [_jsxs("div", { className: "section-header", children: [_jsx("span", { className: "character-name enemy-name", children: enemyName }), _jsx("span", { className: "enemy-icon", children: "\uD83E\uDDA0" })] }), _jsxs("div", { className: "hp-bar-container", children: [_jsx("div", { className: "hp-bar enemy", children: _jsx("div", { className: "hp-fill", style: { width: `${enemyPercent}%` } }) }), _jsxs("span", { className: "hp-text", children: [enemyHp, "/", enemyMaxHp] })] })] })] }), isFighting && (_jsxs("div", { className: "battle-status fighting", children: [_jsx("div", { className: "status-icon", children: "\u2694\uFE0F" }), _jsx("div", { className: "status-text", children: "\u6218\u6597\u4E2D!" })] })), isWon && (_jsxs("div", { className: "battle-result victory", children: [_jsx("div", { className: "result-icon", children: "\u2728" }), _jsx("div", { className: "result-text", children: "\u80DC\u5229!" })] })), isLost && (_jsxs("div", { className: "battle-result defeat", children: [_jsx("div", { className: "result-icon", children: "\uD83D\uDC80" }), _jsx("div", { className: "result-text", children: "\u5931\u8D25!" })] }))] }));
};
